import type { Achievement } from '@/types';

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_workout',
    name: 'First Blood',
    description: 'Complete your first workout',
    icon: 'zap',
    color: '#00e5ff',
    unlocked: false,
  },
  {
    id: 'streak_3',
    name: '3 Day Streak',
    description: 'Work out 3 days in a row',
    icon: 'trending-up',
    color: '#00ff7f',
    unlocked: false,
    progress: 0,
    maxProgress: 3,
  },
  {
    id: 'streak_7',
    name: 'Week Warrior',
    description: '7 day workout streak',
    icon: 'award',
    color: '#ffd700',
    unlocked: false,
    progress: 0,
    maxProgress: 7,
  },
  {
    id: 'streak_30',
    name: 'Consistency Beast',
    description: '30 day workout streak',
    icon: 'shield',
    color: '#ff6b35',
    unlocked: false,
    progress: 0,
    maxProgress: 30,
  },
  {
    id: 'chest_day',
    name: 'Chest Day Complete',
    description: 'Complete a chest-focused workout',
    icon: 'target',
    color: '#e040fb',
    unlocked: false,
  },
  {
    id: 'leg_day',
    name: 'Leg Day Survivor',
    description: 'Complete a leg-focused workout',
    icon: 'activity',
    color: '#ff4081',
    unlocked: false,
  },
  {
    id: 'no_skip_week',
    name: 'No Skip Week',
    description: 'Complete all planned workouts in a week',
    icon: 'check-circle',
    color: '#00e5ff',
    unlocked: false,
  },
  {
    id: 'new_pr',
    name: 'New PR',
    description: 'Exceed a previous best exercise volume',
    icon: 'trending-up',
    color: '#00ff7f',
    unlocked: false,
  },
  {
    id: 'weight_progress',
    name: 'Weight Goal Progress',
    description: 'Log 5 body weight entries',
    icon: 'bar-chart-2',
    color: '#ffb800',
    unlocked: false,
    progress: 0,
    maxProgress: 5,
  },
  {
    id: 'total_10',
    name: 'Committed',
    description: 'Complete 10 total workouts',
    icon: 'star',
    color: '#ffd700',
    unlocked: false,
    progress: 0,
    maxProgress: 10,
  },
  {
    id: 'total_50',
    name: 'Forge Master',
    description: 'Complete 50 total workouts',
    icon: 'cpu',
    color: '#00e5ff',
    unlocked: false,
    progress: 0,
    maxProgress: 50,
  },
];
